name: Build Mac Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_mac:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Updated to v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B build -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Zip the Plugin
      run: |
        cd build/CompFilter_artefacts/Release/VST3
        zip -r -y CompFilter_Mac.zip CompFilter.vst3

    - name: Upload Artifact
      uses: actions/upload-artifact@v4 # Updated to v4
      with:
        name: Mac-VST3-Build
        path: build/CompFilter_artefacts/Release/VST3/CompFilter_Mac.zip
